version: '3.8'

services:
  api:
    build: .
    container_name: ecr_auth_api
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://postgres:dpostgres@postgres:5432/ecr_auth?schema=public
      - JWT_SECRET=secret
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_REDIRECT_URI=http://localhost:3333/auth/google/callback
      - PORT=3333
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: ecr_auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dpostgres
      POSTGRES_DB: ecr_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
