version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ecr_auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dpostgres
      POSTGRES_DB: ecr_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
